global:
  scrape_interval: 1s
  
scrape_configs:
  - job_name: prometheus 
    static_configs:
      - targets:
        - 172.17.0.1:8080
        - 172.17.0.1:8081
        - 172.17.0.1:8082
        - 172.17.0.1:8083

            

